### ISSUE TITLE
Support Sublime Text 3

### ISSUE THREAD

**Issue by johnthagen** [kudanai/sublime-chordpro#1]
Are there are plans to support Sublime Text 3?

**Comment by kudanai** [comment]
not particularly at the moment. I haven’t updated this in a while so I’m not sure if I will continue it. I may take a look later if I have time though. If you want to contribute please do so?

**Comment by johnthagen** [comment]
@kudanai So it turns out that this does actually work for Sublime Text 3.  I'll work on a PR to fix the README.

The problem I had was that a popular app for iOS and Android, SongBook, uses `.pro` by default for its file formats (https://linkesoft.com/songbook/android.html), which isn't listed in this plugin's default extensions.  I'll make a PR to add it to the default list of file extentions.
